sudo: required
services:
  - docker
language: ruby
rvm:
  - 2.3.6

matrix:
    allow_failures:

cache: bundler

install:
    - docker build -t 2maz/apaka .
              --build-arg PKG_BRANCH="${TRAVIS_BRANCH}"
              --build-arg PKG_PULL_REQUEST="${TRAVIS_PULL_REQUEST}"
              --build-arg PKG_PULL_REQUEST_BRANCH="${TRAVIS_PULL_REQUEST_BRANCH}"
script:
    - docker run --privileged 2maz/apaka /bin/sh -c "cd /home/docker/apaka/; BUNDLE_GEMFILE=/home/docker/apaka/test/workspace/.autoproj/Gemfile rake test"
