name: ubuntu-20.04
on: [push]
jobs:
  unittests:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: current_branch

      - name: Build 20.04
        run: docker build -t 2maz/apaka:20.04 -f Dockerfile.2004 . --build-arg PKG_BRANCH=${{ steps.current_branch.outputs.branch }}

      - name: Test-on-ubuntu:20.04
        run: docker run --privileged 2maz/apaka:20.04 /bin/sh -c "cd /home/docker/apaka/; BUNDLE_GEMFILE=/home/docker/apaka/test/workspace/.autoproj/Gemfile rake test"
